name: Check & Build Kernel

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: Swatinem/rust-cache@v1

      - name: Run Check
        run: cargo kcheck --verbose

      - name: Build Clippy
        run: cargo kclippy --verbose

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [debug, release]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: Swatinem/rust-cache@v1

      - name: Build
        run: cargo kbuild_${{ matrix.build_type }} --verbose

      - name: Generate Bootable Image
        run: cargo genimage_${{ matrix.build_type }}

      - name: Finish up
        run: ls -lah --color=always ./bin/${{ matrix.build_type }}/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: kust-kernel-${{ matrix.build_type }}
          path: ./bin/${{ matrix.build_type }}/
